# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dial_out_pb2 as dial__out__pb2
import gnmi_pb2 as gnmi__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dial_out_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class gNMIDialOutStub(object):
    """gNMIDialOut defines a service which is used by a target system (typically a
    network element) to initiate connections to a client (collector). The server
    is implemented at the collector, such that the target can initiate connections
    to the collector, based on a configured set of telemetry subscriptions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.stream_stream(
                '/gnmi.sonic.gNMIDialOut/Publish',
                request_serializer=gnmi__pb2.SubscribeResponse.SerializeToString,
                response_deserializer=dial__out__pb2.PublishResponse.FromString,
                _registered_method=True)


class gNMIDialOutServicer(object):
    """gNMIDialOut defines a service which is used by a target system (typically a
    network element) to initiate connections to a client (collector). The server
    is implemented at the collector, such that the target can initiate connections
    to the collector, based on a configured set of telemetry subscriptions.
    """

    def Publish(self, request_iterator, context):
        """Publish allows the target to send telemetry updates (in the form of
        SubscribeResponse messaages, which have the same semantics as in the
        gNMI Subscribe RPC, to a client. The client may optionally return the
        PublishResponse message in response to the dial-out connection from the
        target as acknowledgement to the SubscribeResponse message

        The configuration of subscriptions associated with the publish RPC may
        be through the OpenConfig telemetry configuration and operational state
        model:
        https://github.com/openconfig/public/blob/master/release/models/telemetry/openconfig-telemetry.yang
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gNMIDialOutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.stream_stream_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=gnmi__pb2.SubscribeResponse.FromString,
                    response_serializer=dial__out__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gnmi.sonic.gNMIDialOut', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gnmi.sonic.gNMIDialOut', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class gNMIDialOut(object):
    """gNMIDialOut defines a service which is used by a target system (typically a
    network element) to initiate connections to a client (collector). The server
    is implemented at the collector, such that the target can initiate connections
    to the collector, based on a configured set of telemetry subscriptions.
    """

    @staticmethod
    def Publish(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gnmi.sonic.gNMIDialOut/Publish',
            gnmi__pb2.SubscribeResponse.SerializeToString,
            dial__out__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
