# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dial_out.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dial_out.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gnmi_pb2 as gnmi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ial_out.proto\x12\ngnmi.sonic\x1a\ngnmi.proto\"i\n\x0fPublishResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x1a\n\x06prefix\x18\x02 \x01(\x0b\x32\n.gnmi.Path\x12\r\n\x05\x61lias\x18\x03 \x01(\t\x12\x18\n\x04path\x18\x04 \x03(\x0b\x32\n.gnmi.Path2R\n\x0bgNMIDialOut\x12\x43\n\x07Publish\x12\x17.gnmi.SubscribeResponse\x1a\x1b.gnmi.sonic.PublishResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dial_out_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHRESPONSE']._serialized_start=42
  _globals['_PUBLISHRESPONSE']._serialized_end=147
  _globals['_GNMIDIALOUT']._serialized_start=149
  _globals['_GNMIDIALOUT']._serialized_end=231
# @@protoc_insertion_point(module_scope)
